### PR TITLE
#63: Add Configuration.BaseUrl

### PR DESCRIPTION
**Pull request by davespoon**
Add BaseUrl property to Configuration
Add tests for BaseUrl

### CODE REVIEW

**Comment by yashaka** [comment]
Looks promising! Will look into this (review PR) probably during next weeks, at most - till the end of first week of Sept

**Comment by davespoon** [comment]
> Looks promising! Will look into this (review PR) probably during next weeks, at most - till the end of first week of Sept

Just noticed there are a lot of unnecessary formatting into my commit on existing code(auto alignment by IDE) - tell me if it's needed to be undone, I'll fix it.

**Comment by yashaka** [comment]
@davespoon, yes, please fix it with another commit on this PR

**Comment by davespoon** [comment]
> @davespoon, yes, please fix it with another commit on this PR
@yashaka done =)

**Pull request merged**
